/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arqudir;

import static arqudir.MetodosFile.arquDir;
import static arqudir.MetodosFile.subDir;
import javax.swing.JOptionPane;

/**
 *
 * @author Jano
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrearDirectorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSalida = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        bComprobarDirectorio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bCreaSubdir = new javax.swing.JButton();
        bCompruebaSubdir = new javax.swing.JButton();
        bArchivoP2 = new javax.swing.JButton();
        bCompuebraP2 = new javax.swing.JButton();
        bListar = new javax.swing.JButton();
        bRuta = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bInfo = new javax.swing.JButton();
        bDarPermiso = new javax.swing.JButton();
        bQuitaPermiso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCrearDirectorio.setText("Crear directorio 'ArqDir'");
        bCrearDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearDirectorioActionPerformed(evt);
            }
        });

        taSalida.setColumns(20);
        taSalida.setRows(5);
        jScrollPane1.setViewportView(taSalida);

        jLabel1.setText("SALIDA:");

        bComprobarDirectorio.setText("Comprobar Directorio");
        bComprobarDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobarDirectorioActionPerformed(evt);
            }
        });

        jButton1.setText("Crear Archivo 'Products1'");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Comprobar Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bCreaSubdir.setText("Crear 'SubDir'");
        bCreaSubdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreaSubdirActionPerformed(evt);
            }
        });

        bCompruebaSubdir.setText("Comprobar Directorio");
        bCompruebaSubdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompruebaSubdirActionPerformed(evt);
            }
        });

        bArchivoP2.setText("Crear 'Products2'");
        bArchivoP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArchivoP2ActionPerformed(evt);
            }
        });

        bCompuebraP2.setText("Comprobar Archivo");
        bCompuebraP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompuebraP2ActionPerformed(evt);
            }
        });

        bListar.setText("Listar");
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });

        bRuta.setText("Mostrar Ruta");
        bRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRutaActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bInfo.setText("Info 'Products1''");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });

        bDarPermiso.setText("Dar Permisos");
        bDarPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDarPermisoActionPerformed(evt);
            }
        });

        bQuitaPermiso.setText("Quitar Permisos");
        bQuitaPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitaPermisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCrearDirectorio)
                            .addComponent(jButton1)
                            .addComponent(bCreaSubdir)
                            .addComponent(bArchivoP2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCompruebaSubdir)
                            .addComponent(jButton2)
                            .addComponent(bComprobarDirectorio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bCompuebraP2)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bQuitaPermiso)
                                    .addComponent(bDarPermiso))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bRuta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bListar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bBorrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bInfo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(51, 51, 51))))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCrearDirectorio)
                            .addComponent(bComprobarDirectorio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCreaSubdir)
                            .addComponent(bCompruebaSubdir))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bArchivoP2)
                            .addComponent(bCompuebraP2)
                            .addComponent(bDarPermiso))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(bListar)
                        .addGap(20, 20, 20)
                        .addComponent(bRuta)
                        .addGap(18, 18, 18)
                        .addComponent(bBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(bInfo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bQuitaPermiso)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MetodosFile.creaArchivo(arquDir.getPath(), "Products1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bCompruebaSubdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompruebaSubdirActionPerformed
        MetodosFile.compruebaDirCMD(subDir.getPath());
    }//GEN-LAST:event_bCompruebaSubdirActionPerformed

    private void bCrearDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearDirectorioActionPerformed
        MetodosFile.creaArquivosdir();
    }//GEN-LAST:event_bCrearDirectorioActionPerformed

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        MetodosFile.listarIO();
    }//GEN-LAST:event_bListarActionPerformed

    private void bCreaSubdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreaSubdirActionPerformed
        MetodosFile.creaSubDir();
    }//GEN-LAST:event_bCreaSubdirActionPerformed

    private void bComprobarDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobarDirectorioActionPerformed
        MetodosFile.compruebaDirCMD(arquDir.getPath());
    }//GEN-LAST:event_bComprobarDirectorioActionPerformed

    private void bArchivoP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArchivoP2ActionPerformed
        MetodosFile.creaArchivo(subDir.getPath(), "Products2");
    }//GEN-LAST:event_bArchivoP2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ruta = arquDir.getPath() + "\\Products1.txt";
        MetodosFile.compruebaDirCMD(ruta);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bCompuebraP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompuebraP2ActionPerformed
        String ruta = subDir.getPath() + "\\Products2.txt";
        MetodosFile.compruebaDirCMD(ruta);
    }//GEN-LAST:event_bCompuebraP2ActionPerformed

    private void bRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRutaActionPerformed
        taSalida.setText("Ruta del primer directorio:\n" + arquDir.getPath());
    }//GEN-LAST:event_bRutaActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed

        int opcion = Integer.parseInt(JOptionPane.showInputDialog(null, "Elija una opción:\n1. Borrar archivo Products1\n2.Borrar archivo Products2\n3.Borrar subDir\n4.Borrar arquDir"));

        switch (opcion) {
            case 1:
                MetodosFile.borrar(arquDir.getPath()+"\\Products1.txt");
                break;
            case 2:
                MetodosFile.borrar(subDir.getPath()+"\\Products2.txt");
                break;
            case 3:
                MetodosFile.borrar(subDir.getPath());
                break;
            case 4:
                MetodosFile.borrar(arquDir.getPath());
                break;
            default:
                JOptionPane.showMessageDialog(null, "Eso no es una opción");
        }

    }//GEN-LAST:event_bBorrarActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        MetodosFile.daInfo(arquDir.getPath()+"\\Products1.txt");
    }//GEN-LAST:event_bInfoActionPerformed

    private void bDarPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDarPermisoActionPerformed
        MetodosFile.daPermisos(arquDir.getPath()+"\\Products1.txt");
    }//GEN-LAST:event_bDarPermisoActionPerformed

    private void bQuitaPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitaPermisoActionPerformed
        MetodosFile.quitaPermisos(arquDir.getPath()+"\\Products1.txt");
    }//GEN-LAST:event_bQuitaPermisoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bArchivoP2;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bComprobarDirectorio;
    private javax.swing.JButton bCompruebaSubdir;
    private javax.swing.JButton bCompuebraP2;
    private javax.swing.JButton bCreaSubdir;
    private javax.swing.JButton bCrearDirectorio;
    private javax.swing.JButton bDarPermiso;
    private javax.swing.JButton bInfo;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bQuitaPermiso;
    private javax.swing.JButton bRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea taSalida;
    // End of variables declaration//GEN-END:variables
}
